version: "3.8"

networks:
  appnet:
    driver: bridge

services:
  # caddy:
  #   image: caddy:latest
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - caddy_data:/data
  #     - ${DATA_FOLDER}/caddy_config:/config
  #     - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
  #   environment:
  #     # Cloudflare API token used by the dns cloudflare challenge in Caddyfile.
  #     # Store this token securely (do not commit to git). You can set it in
  #     # your environment or a docker secret and inject it here.
  #     - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
  website:
    image: nginx:latest
    container_name: website
    ports:
      - "8090:80"
    volumes:
      - ./website/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - appnet
    restart: unless-stopped

  n8n:
    build:
      context: .
      dockerfile: ./docker_images/n8n.dockerfile
    container_name: n8n
    restart: always
    ports:
      # Do not publish n8n's port to the host. Caddy (in the same Docker
      # network) will reverse-proxy to the 'n8n' service internally.
      # Removing the host mapping prevents access via host_ip:5678.
      # If you want to expose for debugging only on localhost, you can use
      # the bind-to-localhost syntax (Docker Engine v20.10+):
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_EDITOR_BASE_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      # Trust proxy ranges (Express syntax: comma-separated, supports CIDR and keywords)
      - N8N_EXPRESS_TRUST_PROXY=loopback,uniquelocal,172.17.0.0/16
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - appnet


volumes:
  # caddy_data:
  #   external: true
  n8n_data:
    external: true
